### ISSUE TITLE
Model fails to load

### ISSUE THREAD

**Issue by AlexanderPezarro** [AlexanderPezarro/DrawAI#2]
Description:
Running the instance using the python virtual environment created with the supplied requirements.txt crashes due to the model failing to be loaded.

Steps to reproduce:
1. Create a new venv in the backend folder and populate it using the requirements.txt
2. Run an instance of DrawAI and attempt to practise
3. View the output of the backend and the lack of result from the instance

**Comment by alexisseppolabat** [comment]
- Could be due formatting issue, i.e., there are two models in the `AI` directory and the `backend` directory.
- Clean up these two dirs and make them one
- Then look into loading each model and see what is causing issues
